development:
      adapter: mysql
      database: fedena_ultimate
      User: anassaeed
      Password: Sooner445

test: &test
      adapter: mysql
      database: fedena_two_new
      User: anassaeed
      Password: Sooner445

production:
      adapter: mysql
      database: fedena_ultimate
      User: anassaeed
      Password: Sooner445
cucumber:
  <<: *test
